language: java
install: true
addons:
  code_climate:
  repo_token: a4f10636fe11cc70f2e038e4df18abe64b17f1f9609a09b86ee2a7c877ef2a36
matrix:
  include:
  - jdk: oraclejdk8
script: ant test jar
env:
  global:
    secure: XpArBRq0bKup5UYe7cOLqBSK4iXkG6p5YMNNBVIWjxHXiRuBxdFu4eXCu03scIzoe/GyXD65grSsZevAekK0lJZAd0/T62n0hfuWxw/NWHD+lbJRuGxNbwcqTvihLs8Np4Cicj7S+aWMZLdUc7eTrvx/nrs13PGUvHwn0eBo/GPrGYD3Jh/zaDG9c4w920tkq8u9telyl5sTF4ElrY2aneQbqRxs7zLLnDtLc+wdvNtfeAdGVD74mRzUSsWP+FFGea4nqA1A7qaXKSvIpdo3ympxZNCTBu3jMAGPSDk7CRnJOZYlLcNqqpeWdsCvPRst4Y57dPhstzv5KicDMuicZHUJddeXCFqtxYxvhj1rvsAud8L79KYDEC+Dux4qvW2uu5B79JwROTJlHdcC7FckikOHcp8KgHXJuwQbtboPemZ22dZvgK+TJKcp/tvvgGScZkJ9jPBwhRjFllblz6X2nRx8UNcHtrIwIP5PnYI1t95yGYlImVuzdv6uWW8uQxCvePCTBPHsBLnRvsT03MBAnbk1I9GiqHZntVWnxQcbcSXzl8gTpgEhSs/PiOimRyaP/WG7+rEOPXZ/n/VdfwvoN4a4p/KVb2mo3WbiLNxtrHYjJoN3+4V/3/nRRI4c6CvS9yHnMqQQ99ZAlKSnMVUpW30y3y6WL7I8tTw3aNr5+38=
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://${GH_TOKEN}:x-oauth-basic@github.com/mitoskalandiel/JokerLibs.git --tags
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Awl994P4STOPDA0lJoBn+645dcz3HkSQ2knIni6MW6zH+FqHVv0PUYkw0eiYQVE1WhJH9dFocnTNXPlvaTUjZExqUaoqfocSyfH9bqCxanzxZQWpwalzYdsnXvsfE39qeKf+WL3oml6z3riz0zbtzJaRh8MkpBwc6N24CQewtygo46FSiYOy6JyRbgPrhjb70l3zRhv11p/yCPPrc6kklnKKtMFwz08Lntl3AfiEKzWC2ym5Teotsiwf0jwCsa8FLHxABHoy3aefH7SEldGnm6/pkWDcyEv6No37oClFUATvIYNpgQDvLnk7U5vDNuimsABnJkI+/C+Kt9NXA81wD2vqWaJy8UM84vW3urOtDKdpl6eStE3I/7DJ7jQtrFv15HHyek4eoc4saVNwaBTcNYIUCLrbfXFm4gg2EXQJUEOMLzqRWJ3J8GUAaGxhtXOCtmvfP1mmZ+NdEYiDfj7z22vqBW1JKmmdn/D89MsUsN6cCjo+J8miAZBwuiNwi6haJMSNWsaI656gYaXSbzbZadpRbflQKLywrU/M6Zn6j1CBGGj4t7ly820WwLMEHbnMH93T6K/KDmCGeHaRBWoGqFMWGEZJCEpgw23ZqPhOMDwM3D+c7PR8wAHkQkyo88f/z3wZCBOtrYb7QaBuAMN9jXaK9Sf5YxEl6/cUc5r9ndU=
  file:
  - dist/JokerLibs.jar
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
