language: java
jdk:
- oraclejdk8
env:
  global:
    secure: Tgafh8T+eP3DVyWJbyvAhwliQFL0R5zT5F6V6qviDlFdA7Xohwg/lssUMNf18KkwScuHVkmpXsirAYX4QkwgHbkdXQYxR5BscwSUVHioqP2HRphij8Y5KkN+ToW1hiiHCl8PLyyM4Dada/1XrUfPUq0LFttGV3gVzEWKSCMzBDPmeTQgNyURyhDbmMOjdz5hCx33ijW4F0qPlnNvdvwbS960t1SqHoAmeJwEHnAZHOTrwyxOEpeTiCKApmUOR3Lv/9wceTTxz4nx9LCP4p3wKaMLH93Vy5Ol6cA/mEQv90pTGDCmX5uGsTx0zYl481xreGCZu7FTYDE7CIXQDqWT1zhgTAyK2w2MgRGKSczxi2Z7e3iS0KxeUjUz27Gf4R946SKbzN9cInMID1FpmlSVuQlcAXq+7Om3m7YI187Dz6TYlq3ggbUpM7e+4onEF5lvMmXQ3V9K8Lvg49bxOGNI7FrOKi9jxMlAMmapQRY6l2aW94AsUub1/ilzPBJSl5WE46HPY1163K9H5rlUSwEuv6o9T99EzqSY/5tYZAi8rCl80bj2kCljE9HU2bV8JMf+LbpdEIK7nQfL3klvJQwRwf7j2hO1JjDrs80SDXMnxHCDMx80qlkWF8SiXDPiYwl1tPR6DLLT5a8Wp2G7KHKDbbocKo+22EKm755s8UYFwJg=
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://github.com/mitoskalandiel/JokerLibs --tags
- ls -R
deploy:
  provider: releases
  api_key: 
      secure: ${GH_TOKEN}
  file: dist/JokerLibs.jar
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
