language: java
install: true
matrix:
  include:
  - jdk: oraclejdk8
script: ant test jar
env:
  global:
    secure: Pw3jvxncJjXEVqw+XS69CtaMj9iKRDXYpU/gOM2cbcC3Dba/fPuXjraUWIwlltv8mAnSfIvfDQiLP9CPM+AyCa/TpDVOqEPOc3KI+48gF/tnZ6oGJh4JXC86C2YqXyVxbbfCQCasL+IkmcNjnMBR39BHpt5kX4IQ4G4aHbRQeOmurooGH39GYh0Zr/Ukvhx9uaezQHC7DM+N3sCRSV5CjY55sv0N1tFk1T83jb2gjlUpTRcHS27k1pep2PM4aMWK1etTCd28L/yBg6TPD1xNGY+0rwUXKD3WMDOXFVe1jGt825O+tJZBPHmOf3cBC4sAiGmmq8Y/W0d1vdClOzhy20UZYjXRfcVSjJ0Ftv6y+FSsGprdOfuhShx6yIHzNxA7u2ZR2bJSok4lft+y3n+Sntz3NjMPuS/LEcl1r8oZ3jgaSFdwbkxfZgMJregKuOfTyBBRtosxcI9/TeagY1ZzDEOmAS1n/NIv6lK5GcFp+FiDKG6PKa1E1s2zT6MHGNMlkYAd6sqJMpakH7xa7ibeq2qHLwcnTGtBsPEfzzzkHCo92kpHM6UXqNUaBZBCqg/F8U8uE4pRi0g7ULQIFTbXt3ONNByzVZHnJsIn2eJcNUc7Obz0cCLHCfTDYFCQU4EHGHeQxJcjf2yKDzfLB8d7MSO2yvdTjx0tnbDYjGgkCQ4=
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://${GH_TOKEN}@github.com/mitoskalandiel/JokerLibs --tags
- ls -R
- printenv
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Awl994P4STOPDA0lJoBn+645dcz3HkSQ2knIni6MW6zH+FqHVv0PUYkw0eiYQVE1WhJH9dFocnTNXPlvaTUjZExqUaoqfocSyfH9bqCxanzxZQWpwalzYdsnXvsfE39qeKf+WL3oml6z3riz0zbtzJaRh8MkpBwc6N24CQewtygo46FSiYOy6JyRbgPrhjb70l3zRhv11p/yCPPrc6kklnKKtMFwz08Lntl3AfiEKzWC2ym5Teotsiwf0jwCsa8FLHxABHoy3aefH7SEldGnm6/pkWDcyEv6No37oClFUATvIYNpgQDvLnk7U5vDNuimsABnJkI+/C+Kt9NXA81wD2vqWaJy8UM84vW3urOtDKdpl6eStE3I/7DJ7jQtrFv15HHyek4eoc4saVNwaBTcNYIUCLrbfXFm4gg2EXQJUEOMLzqRWJ3J8GUAaGxhtXOCtmvfP1mmZ+NdEYiDfj7z22vqBW1JKmmdn/D89MsUsN6cCjo+J8miAZBwuiNwi6haJMSNWsaI656gYaXSbzbZadpRbflQKLywrU/M6Zn6j1CBGGj4t7ly820WwLMEHbnMH93T6K/KDmCGeHaRBWoGqFMWGEZJCEpgw23ZqPhOMDwM3D+c7PR8wAHkQkyo88f/z3wZCBOtrYb7QaBuAMN9jXaK9Sf5YxEl6/cUc5r9ndU=
  file:
  - dist/JokerLibs.jar
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
